<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Leverageplan-3</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>857f36ea-6bf1-4078-b8d0-3e41165a4a18</testSuiteGuid>
   <testCaseLink>
      <guid>7b8e4afb-e7e4-4a5b-bac9-5c5f7d089f95</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard_Lenovo/Dashboard_Login</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>3360f779-18db-4d82-89ef-599d145bccb2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard_Lenovo/Dashboard_Planfloder/Dashboard_1Plans</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>259b3608-4f2b-45a0-ae1d-99878612b8af</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>83f1a35b-b71d-4a62-a873-9748b324272b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard_Lenovo/Dashboard_Planfloder/Dashboard_PlanActions</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a678353e-e27e-40c9-85f5-2e061697dd73</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>73c001ca-ee26-483b-8302-432adcbc59e2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard_Lenovo/Dashboard_date</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>49d30139-4115-4ef8-91f5-3f926c4d5a5d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6861477b-0a57-40fe-b40e-e9757bd50ab4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard_Lenovo/Dashboard_Participant</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e941333-c891-43f4-a18d-d08f7acbf3f1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>389ec4b9-bcd6-4b4d-a8b3-5ca5acab69e1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard_Lenovo/Dashboard_widgets/Widget1_QTD_CPS_Attainment</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d0aa7861-5fd7-4c4c-91aa-6b9f568addfc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>579a4207-a3dc-4904-a5e6-d3e9d042e3ad</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a7983758-0da2-450b-b4fb-592dbfcb96bc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard_Lenovo/Dashboard_widgets/Widget2_Myprofile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>957994c4-9ba1-4d07-88d7-d37b5cfe63de</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e01b6ce1-5e75-4a0d-a57e-7a32e433be38</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e40c14be-4afe-4489-aeb2-0587b3929d11</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>108ae585-3de8-4309-aa4c-a49796b22b9d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>99b4681f-6002-4e64-ac66-a816ae38a106</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>95d64a2e-bf7a-4919-88b9-f77dbb79080c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d71c7ba8-8dbf-4b3a-a5cc-666dda52f511</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard_Lenovo/Dashboard_widgets/Widget3_Percent_of_TI</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>96b86d4c-ac35-4323-a92f-75ec71650a20</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e84abb14-0e13-4aba-b9f6-f016650ce659</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9478d7a4-90c5-44d1-bd71-4c0ea0f50e13</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d2d0ced-c48b-4466-b781-0252e2380cba</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>78da236a-95de-4841-a855-046f9140d851</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard_Lenovo/Dashboard_widgets/Widget4_Element_1_Attainment</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c8d945f2-6f2d-4682-abcd-cbc2142f9373</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>01271e99-2932-4b31-8ae7-78890018b283</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>36dd0e26-f946-469c-97b9-e9ae0420819e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d733f406-8047-425f-a167-8ea22822b52e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bdb418ea-ad92-400b-8429-bb8de0d8d1ef</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard_Lenovo/Dashboard_widgets/Widget5_Element_2_attainment</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6ae00954-43d9-47aa-841b-96d31d685e33</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>23f03d92-bb60-451b-972a-8846cc0edf4b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85a9daed-a0d5-43db-8659-55567e39425a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>667dc862-8a71-42f9-8eb0-7d23f013de67</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a0a1e330-0167-4ec5-9941-68d01f25b87e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard_Lenovo/Dashboard_widgets/Widget6_Element_3_Attainment</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a50359c9-88cf-4dcc-9236-73ba43169d7f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>26abfbed-dc76-42c8-a2b6-b215e0947595</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64df6a04-61c7-49d2-9e48-79afb119653f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf521681-f1de-4e17-b7f6-91ab68281857</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>85e1b7f0-6587-485a-82df-92f8064834de</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard_Lenovo/Dashboard_widgets/Widget7_attainment and quota/Widget7_1_QTD_CPSandELEMENT1DATA</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>afc722e0-eed9-4806-98dc-f20a451e5c99</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8a5f33db-dfb0-4a4d-a01a-ed2926fd182a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2dc4ef96-a118-4388-ab77-7aa1e01b517f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>99c01cb3-87c8-41d0-9135-94e5203ef764</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a35b2ca-04dd-43f6-8309-01148bf94c06</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dd91e6e4-93b5-4062-9029-1d6c68df4e34</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>befa4ab1-0398-4982-b678-0f4e9601377c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>09cc3ebb-4911-416a-8471-ffd5ee578930</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard_Lenovo/Dashboard_widgets/Widget7_attainment and quota/Widget7_2_Element2val</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0d57cf39-7b4f-4568-b934-1738408475bc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e9620a8e-ef49-4d93-bdc9-88fe5a5b7057</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e3b9aead-f2af-48f0-a7c6-c232d4127842</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1b7f22ca-a37f-4642-8754-9ae44f212925</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard_Lenovo/Dashboard_widgets/Widget7_attainment and quota/Widget7_3_Element3Val</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e25b52af-fd3f-4f50-8776-ab074c114a9b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d27e65f-d04f-4aed-8362-96697adda4ba</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d5593e7c-5d3a-42b8-b426-57d243fbc137</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3efb2e62-6d0d-42c8-b243-0efaaec47894</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard_Lenovo/Dashboard_widgets/Widget8_currentyearpayments</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7dc86ff6-0639-4a75-8148-5f6e5dbfb8ee</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
