<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PlanSelection</name>
   <tag></tag>
   <elementGuidId>f131912e-8f68-439e-9e2b-5a33ef4c4c6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@ng-show='!vm.loading']//tbody/tr</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@ng-show='!vm.loading']//tbody/tr</value>
   </webElementProperties>
</WebElementEntity>
