<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Showmore_button</name>
   <tag></tag>
   <elementGuidId>942ca03a-094a-4a26-ab1e-7680e80fea06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@ng-disabled='vm.loadingMore']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@ng-disabled='vm.loadingMore']</value>
   </webElementProperties>
</WebElementEntity>
